### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by chaitanyabaranwal**

### CODE REVIEW

**Comment by poush** [comment]
Provide a proper name to the PR, provide a deployment link.

**Review by poush — CHANGES_REQUESTED** [review]
Good work! 
Please add .pyc files to gitignore. Also, provide a readme file with instructions to install and run your code. Tell about the project with some screenshots or deployment link in the readme.

**Review by chaitanyabaranwal — COMMENTED** [review]
Thanks, I'll work on the comments. However, I am not well-versed with deployment. Do I HAVE to deploy the app or some screenshots would do?

**Comment by poush** [comment]
@chaitanyabaranwal Deployment is not necessary. Feel free to learn and give it a try anytime. Screenshots are completely fine.

**Pull request closed without merging**
