### PR TITLE
Add Hello Fossasia  - ParthPratim

### PR DESCRIPTION
**Pull request by ParthPratim**
I am adding my Flask Simple Form Fossasia GCI Project .

### CODE REVIEW

**Comment by anshumanv** [comment]
Have you deployed this on Heroku? If yes, please provide that link here. Thanks

**Comment by ParthPratim** [comment]
Deployment Link : https://hello-fossasia.herokuapp.com/

**Review by anshumanv — APPROVED** [review]
LGTM

**Review by djmgit — APPROVED** [review]
Nice work :+1:

**Review by rupav — APPROVED** [review]
Very cool UI, great work 🎉

**Comment by ParthPratim** [comment]
Thanks everyone

**Pull request merged**
