### PR TITLE
Adds SimpleFlaskForm of abishekvashok

### PR DESCRIPTION
**Pull request by abishekvashok**
Adds simple flask form which was created by me during GCI

### CODE REVIEW

**Review by 0x48piraj — COMMENTED** [review]
Sub module ?

**Comment by abishekvashok** [comment]
See the diff in the commit, it is a program so a sub module, github sees like that :)

**Comment by 0x48piraj** [comment]
Thank you for telling me @abishekvashok :blush:

**Review by 0x48piraj — APPROVED** [review]

**Comment by abishekvashok** [comment]
Ping @fossasia/website-admins

**Review by vaibhavsingh97 — COMMENTED** [review]
You can simply add one sub-repo instead of submodule. As we can't see the diff of your code

**Comment by abishekvashok** [comment]
@vaibhavsingh97 I just copy pasted the repo inside. Let me see, I guess the .git folder must have been the cause.

**Comment by vaibhavsingh97** [comment]
@abishekvashok Any update on this?

**Comment by abishekvashok** [comment]
@vaibhavsingh97 on the way

**Comment by abishekvashok** [comment]
@vaibhavsingh97 @rupav  done :)

**Comment by rupav** [comment]
Deploy link please.

**Comment by abishekvashok** [comment]
Can't provide one osrry

**Comment by rupav** [comment]
@vaibhavsingh97  what should we do to this PR then ? @abishekvashok because of time or any other reason ?

**Comment by abishekvashok** [comment]
@rupav note i havent done the task. I cant claim and i guess ii wont.

**Comment by anshumanv** [comment]
Should I close the PR @abishekvashok then?

**Comment by abishekvashok** [comment]
@anshumanv it's your wish.

**Comment by anshumanv** [comment]
The app looks good and I think this should be merged irrespective of the task, probably you can provide test links and all after things are chilled out after GCI. @abishekvashok

**Comment by rupav** [comment]
Yes agreed with @anshumanv . @abishekvashok you can even provide us with screen shots of your app after GCI.

**Comment by abishekvashok** [comment]
@rupav sure. I never did this for GCI. Just out of the love for the community. It is the same for all my commits.

**Pull request merged**
