### PR TITLE
Added files for simple flask web form

### PR DESCRIPTION
**Pull request by chaitanyabaranwal**

### CODE REVIEW

**Review by rupav — APPROVED** [review]
great Work! 🎉
your deployment link is giving correct result and satisfies the GCI task.
Also can you please squash your 2 commits into 1?
Since this Pull Request is made for a single taks, we need only 1 commit (to keep commit history clean).
You can do this by commands on git terminal:
` git rebase -i HEAD~2`
Change the 'pick' on 2nd commit/line to 's'
Save the file.
Then `git push -f origin`.

**Comment by chaitanyabaranwal** [comment]
Hey! I didn't quite get how to squash the commits in a single one.

**Comment by rupav** [comment]
Ok. What problems are you facing @chaitanyabaranwal ? I will help you in that.

**Review by djmgit — APPROVED** [review]
Nice work :+1:

**Review by isuruAb — COMMENTED** [review]
Hi @chaitanyabaranwal .what is the tool you use ? GitBash or GUI version?

**Review by tabesin — APPROVED** [review]

**Pull request merged**
